# Generated by Django 3.0.5 on 2020-07-01 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0002_auto_20200628_1557'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Staff',
        ),
    ]
