# Generated by Django 3.0.5 on 2020-06-28 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Diagnosticmaster',
            fields=[
                ('ws_test_id', models.AutoField(primary_key=True, serialize=False)),
                ('ws_test_name', models.CharField(max_length=255)),
                ('ws_charge', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Diagnostictest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ws_pat_id', models.IntegerField()),
                ('ws_test_id', models.IntegerField()),
            ],
        ),
    ]
