# Generated by Django 3.0.5 on 2020-06-28 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Medicinestock',
            fields=[
                ('ws_pat_id', models.AutoField(primary_key=True, serialize=False)),
                ('ws_med_name', models.CharField(max_length=255)),
                ('ws_qty', models.IntegerField()),
                ('ws_price', models.FloatField()),
            ],
        ),
    ]
