# Generated by Django 3.0.5 on 2020-06-29 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacist', '0002_auto_20200628_1319'),
    ]

    operations = [
        migrations.RenameField(
            model_name='medicinemaster',
            old_name='ws_qty',
            new_name='ws_stock_qty',
        ),
    ]
